Update to process XML files without requiring directory changes.
Changing directory seems to conflict with cabal/ghc, especially with
increased jobcount, resulting in periodic failures like:

src/Dismantle/ARM/T32.hs:1:1: error:
    Exception when trying to run compile-time code:
      data/ISA_v85A_AArch32_xml_00bet9: changeWorkingDirectory: does not exist (No such file or directory)
    Code: genISA
            (isa "T32")
            "data/ISA_v85A_AArch32_xml_00bet9"
            "t32_encindex.xml"
            "data/Parsed/arm_instrs.sexpr"
            "T32.log"